#pragma config(Motor,	 port1,						collectleft,	 tmotorVex393_HBridge, openLoop)
#pragma config(Motor,	 port2,						elevateleft,	 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port3,						driverightback, tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port4,						driveleftfront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port5,						shootL,				 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port6,						shootR,				 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port7,						driveleftback, tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port8,						driverightfront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port9,						elevateright,	 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port10,					collectright,	 tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

/*


*/

task main()	{

	while (true) {



	} // END while true
} // END task main



/*
__				__				_								 __	 __ _			_			_ _
\ \			 / /__	___| |_ ___	 _ __		|	 \/	 (_) __| | __| | | ___
 \ \ /\ / / _ \/ __| __/ _ \| '_ \	| |\/| | |/ _` |/ _` | |/ _ \
	\ V	 V /	__/\__ \ || (_) | | | | | |	 | | | (_| | (_| | |	__/
	 \_/\_/ \___||___/\__\___/|_| |_| |_|	 |_|_|\__,_|\__,_|_|\___|
There's No I in Team.

But there is also no I in myself... wierd bro

There's No Playground in Work

*/
